# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'surveyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  # Pods for surveyApp

  target 'surveyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'surveyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!


end
